let devices=[],assignments=[],vehicles=[],locations=[],knoxLocations=[],map,markers=[],pairLayers=[];
const $=id=>document.getElementById(id); const get=async(url,opt)=>{const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||d.message||`Request failed (${r.status})`);return d};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function num(v){v=Number(v);return Number.isFinite(v)?v:null}
function parseCSV(t){t=t.replace(/^\uFEFF/,'');let rows=[],row=[],cell='',q=false;for(let i=0;i<t.length;i++){let c=t[i],n=t[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const h=rows.shift()||[];return rows.filter(r=>r.some(v=>String(v).trim())).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]||''])))}
const assignmentFor=imei=>assignments.find(a=>String(a.imei)===String(imei))||{};
function hav(a,b){const R=3958.7613,rad=Math.PI/180,dlat=(b.lat-a.lat)*rad,dlon=(b.lon-a.lon)*rad,x=Math.sin(dlat/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function samsaraFor(a){return locations.find(x=>String(x.vehicleId)===String(a.samsaraVehicleId))||locations.find(x=>String(x.name||'').toLowerCase()===String(a.samsaraVehicleName||'').toLowerCase())||locations.find(x=>String(x.name||'').toLowerCase()===String(a.truck||'').toLowerCase())||null}
function knoxFor(imei){return knoxLocations.find(x=>String(x.imei)===String(imei))||null}
function normalizeKnox(x){const d=x?.data||x?.result||x||{},lat=num(d.latitude??d.lat??d.location?.latitude),lon=num(d.longitude??d.lng??d.lon??d.location?.longitude);return lat===null||lon===null?null:{lat,lon,updatedAt:d.updatedAt??d.timestamp??null}}
function pair(a){const s=samsaraFor(a),k=knoxFor(a.imei);if(!s&&!k)return{status:'No GPS',distance:null,samsara:null,knox:null};if(!s)return{status:'Truck GPS missing',distance:null,samsara:null,knox:k};if(!k)return{status:'Tablet GPS missing',distance:null,samsara:s,knox:null};const slat=num(s.location?.latitude??s.latitude),slon=num(s.location?.longitude??s.longitude);if([slat,slon,k.lat,k.lon].some(v=>v===null))return{status:'GPS unavailable',distance:null,samsara:null,knox:null};const d=hav({lat:slat,lon:slon},{lat:k.lat,lon:k.lon});return{status:d<=.5?'Matched':d<=2?'Close':'Mismatch',distance:d,samsara:{lat:slat,lon:slon},knox:k}}
function statusClass(s){return s==='Matched'?'ok':s==='Mismatch'?'bad':s==='Close'?'warn':''}
function searchText(){return ($('search')?.value||'').trim().toLowerCase()}
function render(){const q=searchText(),f=$('filter')?.value||'all';const rows=devices.filter(d=>{const a=assignmentFor(d['Common IMEI/MEID']);const txt=[d['Common IMEI/MEID'],d['Common Serial Number'],d['Common Market Name'],a.driver,a.truck,a.samsaraVehicleId,a.samsaraVehicleName].join(' ').toLowerCase(),assigned=!!(a.driver||a.truck||a.samsaraVehicleId);return(!q||txt.includes(q))&&(f==='all'||(f==='assigned'?assigned:!assigned))});const assigned=assignments.filter(a=>a.driver||a.truck||a.samsaraVehicleId);$('assignedCount').textContent=assigned.length;$('assignmentViewCount').textContent=assigned.length;$('liveNavCount').textContent=locations.length;$('alertNavCount').textContent=assigned.map(pair).filter(p=>p.status==='Mismatch').length;$('vehicleCount').textContent=vehicles.length;$('liveCount').textContent=locations.length;const ps=assigned.map(pair);$('matchCount').textContent=ps.filter(p=>p.status==='Matched').length;$('mismatchCount').textContent=ps.filter(p=>p.status==='Mismatch').length;$('rows').innerHTML=rows.map(d=>{const id=d['Common IMEI/MEID'],a=assignmentFor(id),p=(a.driver||a.truck||a.samsaraVehicleId)?pair(a):null;return `<tr><td><b>${esc(id)}</b><small>${esc(d['Common Serial Number'])} · ${esc(d['Common Market Name'])}</small></td><td>${esc(a.driver||'—')}</td><td>${esc(a.truck||'—')}</td><td>${esc(a.samsaraVehicleName||a.samsaraVehicleId||'—')}</td><td><span class="pill ${a.imei?statusClass(p?.status):'warn'}">${a.imei?(p?.status||'Checking'):'Unassigned'}</span></td><td><button class="small-btn" onclick="openAssign('${esc(id)}')">Edit</button></td></tr>`}).join('')||'<tr><td colspan="6">No tablets found.</td></tr>';drawLocations()}
function fillImeis(){$('imei').innerHTML=devices.map(d=>`<option value="${esc(d['Common IMEI/MEID'])}">${esc(d['Common IMEI/MEID'])} · ${esc(d['Common Serial Number'])}</option>`).join('')}
function fillVehicles(){$('samsaraVehicle').innerHTML='<option value="">— none —</option>'+vehicles.map(v=>`<option value="${esc(v.id)}">${esc(v.name||v.id)}</option>`).join('')}
function openAssign(imei=''){ $('modal').classList.remove('hidden');if(imei)$('imei').value=imei;const a=assignmentFor($('imei').value);$('driver').value=a.driver||'';$('truck').value=a.truck||'';$('notes').value=a.notes||'';fillVehicles();$('samsaraVehicle').value=a.samsaraVehicleId||'' }
function closeAssign(){$('modal').classList.add('hidden')}
async function saveAssign(e){e.preventDefault();const imei=$('imei').value,d=devices.find(x=>String(x['Common IMEI/MEID'])===String(imei)),sel=$('samsaraVehicle'),v=vehicles.find(x=>String(x.id)===String(sel.value));const rec=await get('/api/assignments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imei,serial:d?.['Common Serial Number']||'',driver:$('driver').value,truck:$('truck').value,samsaraVehicleId:sel.value,samsaraVehicleName:v?.name||'',notes:$('notes').value})});const i=assignments.findIndex(x=>x.imei===imei);if(i>=0)assignments[i]=rec;else assignments.push(rec);closeAssign();render();await syncLocations(true)}
async function syncSamsara(silent=false){if($('mapStatus'))$('mapStatus').textContent='Syncing…';try{vehicles=(await get('/api/samsara/vehicles')).data||[];locations=(await get('/api/samsara/locations')).data||[];fillVehicles();await syncKnox(silent);$('lastSync').textContent='Last sync: '+new Date().toLocaleTimeString();if($('mapStatus'))$('mapStatus').textContent='LIVE • '+locations.length+' trucks • '+new Date().toLocaleTimeString();render()}catch(e){if($('mapStatus'))$('mapStatus').textContent='Samsara API error';if(!silent)alert(e.message)}}
async function syncLocations(silent=false){try{locations=(await get('/api/samsara/locations')).data||[];await syncKnox(silent);render()}catch(e){if(!silent)alert(e.message)}}
async function syncKnox(silent=true){const as=assignments.filter(a=>a.imei&&(a.truck||a.samsaraVehicleId));if(!as.length){knoxLocations=[];return}try{const r=await get('/api/knox/locations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({devices:as.map(a=>({imei:a.imei,mobileId:a.imei}))})});knoxLocations=(r.locations||[]).map(x=>{const n=normalizeKnox(x);return n?{imei:String(x.imei||x.mobileId||''),...n}:null}).filter(Boolean);$('knoxStatus').textContent=knoxLocations.length+' tablet GPS'}catch(e){knoxLocations=[];$('knoxStatus').textContent=e.message.includes('not configured')?'Knox API not configured':'Knox GPS unavailable'}}
function clearMap(){window.markers=markers;markers.forEach(m=>map.removeLayer(m));pairLayers.forEach(x=>map.removeLayer(x));markers=[];pairLayers=[]}
function truckIcon(){return L.divIcon({className:'fleet-truck-icon',html:'<div class="map-truck live-marker">🚛</div>',iconSize:[46,46],iconAnchor:[23,23],popupAnchor:[0,-23]})}
function tabletIcon(){return L.divIcon({className:'fleet-tablet-icon',html:'<div class="map-tablet live-marker">📱</div>',iconSize:[40,40],iconAnchor:[20,20],popupAnchor:[0,-20]})}
function addTruck(x,a=null){const lat=num(x.location?.latitude??x.latitude),lon=num(x.location?.longitude??x.longitude);if(lat===null||lon===null)return;const m=L.marker([lat,lon],{icon:truckIcon()}).addTo(map).bindPopup(`<div class="fleet-popup"><div class="popup-title">🚛 ${esc(a?.truck||x.name||x.vehicleId||'Truck')}</div><div class="popup-row"><span>Driver</span><b>${esc(a?.driver||'—')}</b></div><div class="popup-row"><span>Samsara GPS</span><b>${lat.toFixed(5)}, ${lon.toFixed(5)}</b></div><div class="popup-row"><span>Updated</span><b>${esc(x.updatedAt||'Live')}</b></div></div>`);markers.push(m);window.markers=markers;return[lat,lon]}
function drawLocations(){if(!map)return;clearMap();const q=searchText();let selected=[];if(q){selected=assignments.filter(a=>[a.imei,a.serial,a.driver,a.truck,a.samsaraVehicleId,a.samsaraVehicleName].join(' ').toLowerCase().includes(q));if(selected.length){selected.forEach(a=>drawPair(a))}else{locations.filter(x=>[x.vehicleId,x.name].join(' ').toLowerCase().includes(q)).forEach(x=>addTruck(x))}}else{locations.forEach(x=>{const a=assignments.find(a=>String(a.samsaraVehicleId)===String(x.vehicleId)||String(a.samsaraVehicleName||'').toLowerCase()===String(x.name||'').toLowerCase()||String(a.truck||'').toLowerCase()===String(x.name||'').toLowerCase());if(a)drawPair(a);else addTruck(x)})}if(markers.length){map.fitBounds(L.featureGroup(markers).getBounds().pad(q?.25:.12))}}
function drawPair(a){const p=pair(a);let pts=[];if(p.samsara){const x=locations.find(v=>String(v.vehicleId)===String(a.samsaraVehicleId));const loc=addTruck(x||{latitude:p.samsara.lat,longitude:p.samsara.lon},a);if(loc)pts.push(loc)}if(p.knox){const m=L.marker([p.knox.lat,p.knox.lon],{icon:tabletIcon()}).addTo(map).bindPopup(`<div class="fleet-popup"><div class="popup-title">📱 Knox Tablet</div><div class="popup-row"><span>IMEI</span><b>${esc(a.imei)}</b></div><div class="popup-row"><span>Driver</span><b>${esc(a.driver||'—')}</b></div><div class="popup-row"><span>Knox GPS</span><b>${p.knox.lat.toFixed(5)}, ${p.knox.lon.toFixed(5)}</b></div></div>`);markers.push(m);window.markers=markers;pts.push([p.knox.lat,p.knox.lon])}if(pts.length===2){const l=L.polyline(pts,{weight:4,opacity:.8,dashArray:p.status==='Matched'?'5 7':'10 7'}).addTo(map).bindPopup(`<div class="fleet-popup"><div class="popup-title">📍 GPS comparison</div><div class="popup-row"><span>Truck</span><b>${esc(a.truck||a.samsaraVehicleName||'—')}</b></div><div class="popup-row"><span>Tablet</span><b>${esc(a.imei)}</b></div><div class="popup-distance">Distance: ${p.distance.toFixed(2)} mi</div><div class="popup-status">Status: ${esc(p.status)}</div></div>`);pairLayers.push(l)}}
async function init(){try{const csv=await fetch('/unified_devices.csv').then(r=>{if(!r.ok)throw new Error('Could not load unified_devices.csv');return r.text()});devices=parseCSV(csv);assignments=await get('/api/assignments');$('deviceCount').textContent=devices.length;fillImeis();map=L.map('map').setView([39.5,-98.35],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);window.map=map;window.markers=markers;$('search').addEventListener('input',render);$('filter').addEventListener('change',render);const h=await get('/api/health');$('health').textContent=h.samsaraConfigured?'Samsara API connected':'Website online • Samsara API not configured';if(h.samsaraConfigured)await syncSamsara(true);else if($('mapStatus'))$('mapStatus').textContent='Add Samsara API';if(!h.knoxConfigured)$('knoxStatus').textContent='Knox API not configured';render()}catch(e){console.error(e);$('health').textContent='Connection error: '+e.message}}



// Public fleet mode (login temporarily disabled)
window.currentUser={username:'guest',displayName:'Fleet Operator',role:'admin'};
if($('userName'))$('userName').textContent='Fleet Operator';
async function bootFleet(){try{await init();}catch(e){console.error(e)}}
bootFleet();
setInterval(()=>{if(document.visibilityState==='visible')syncSamsara(true)},5000);
